added auto strategy

diff --git a/eskb_doc_vac b/eskb_doc_vac
--- a/eskb_doc_vac
+++ b/eskb_doc_vac
@@ -9,6 +9,9 @@ SHNAME=$(basename "$0")
 
 CONFIG=${ESKB_CONFIG:-_$SHNAME.config}
 
+# Size in bytes for 'auto' strategy to switch from 'whole' to 'bookmark1'
+AUTO_THRESHOLD=500000
+
 REQUIRED_TOOLS="curl pdftk jq sed awk cut grep"
 
 #############################################################################
@@ -21,7 +24,7 @@ REQUIRED_TOOLS="curl pdftk jq sed awk cut grep"
 ##
 ## Key entries:
 ##  #es_url - Elasticsearch URL
-##  #strategy - Excerpt strategy: How to divide (chunk) large PDFs: whole, page, bookmark1
+##  #strategy - Excerpt strategy: How to divide (chunk) large PDFs: auto, whole, page, bookmark1
 ##  user - curl User:PW config option
 ##  header - headers curl should send, please leave untouched
 do_config() {
@@ -33,7 +36,7 @@ do_config() {
 
         cat >"$CONFIG" <<_EOM_
 #es_url "$ESURL"
-#strategy "bookmark1"
+#strategy "auto"
 #es_inference_name "$SHNAME-e5-model"
 #es_pipeline_name "$SHNAME-pipeline"
 #es_ml_max_alloc "2"
@@ -338,14 +341,16 @@ do_remove_all() {
 ## Reads PDF file (File_Name) and adds each excerpt as its own doc to the index (Index_Name)
 ## Usage: ... read1_pdf <Index_Name> <File_Name>
 do_read1_pdf() {
+    # Due to 'auto' strategy, we need to reset this every iteration
     STRATEGY=$(get_conf strategy)
-    ESPL_NAME=$(get_conf es_pipeline_name)
+
+    ESPL_NAME="${ESPL_NAME:=$(get_conf es_pipeline_name)}"
     IDX=${1?Target index required. See $0 help read1_pdf}
     PDF=${2?PDF file required. See $0 help read1_pdf}
 
     # Validate strategy
     case "$STRATEGY" in
-        whole|page|bookmark*) ;;
+        auto|whole|page|bookmark*) ;;
         *)
             echo "ERROR: Invalid excerpt strategy: $STRATEGY"
             exit 1
@@ -384,8 +389,25 @@ do_read_pdf() {
 
 # Note all these function will reuse variables that should be set in their caller
 
+_read_pdf_by_auto() {
+    PDF_SIZE=$(stat -f %z "$PDF")
+
+    if [ "$?" != 0 ]; then
+        echo "Failed to fetch PDF file size"
+        exit 1
+    fi
+
+    if [ "$PDF_SIZE" -gt "$AUTO_THRESHOLD" ]; then
+        STRATEGY=bookmark1
+        _read_pdf_by_bookmark "$@"
+    else
+        STRATEGY=whole
+        _read_pdf_by_whole "$@"
+    fi
+}
+
 _read_pdf_by_whole() {
-    ES=$(get_conf es_url)
+    ES="${ES:=$(get_conf es_url)}"
 
     PDF_NAME=$(basename "$PDF")
     echo "Read file '$PDF_NAME' into '$IDX' as a whole document on: $ES"
@@ -397,7 +419,7 @@ _read_pdf_by_whole() {
 }
 
 _read_pdf_by_page() {
-    ES=$(get_conf es_url)
+    ES="${ES:=$(get_conf es_url)}"
 
     PDF_NAME=$(basename "$PDF")
     echo "Read file '$PDF_NAME' into '$IDX' using per page, on: $ES"
@@ -418,7 +440,7 @@ _read_pdf_by_page() {
 # BookmarkBegin
 # ...
 _read_pdf_by_bookmark() {
-    ES=$(get_conf es_url)
+    ES="${ES:=$(get_conf es_url)}"
     BKL=${STRATEGY#bookmark}
 
     PDF_NAME=$(basename "$PDF")
@@ -527,8 +549,6 @@ get_conf() {
     fi
     local ITEM=${1? config item required}
 
-#     sed -Ene 's/#(es_)?url // p' < $CONFIG | tr -d '"'
-# /\ Mine  vs. \/ GenAI
     grep -E "^#$ITEM" "$CONFIG" | cut -d'"' -f2
 }
 
